services:
  genome-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genome-analysis
    restart: unless-stopped
    environment:
      - XDG_CACHE_HOME=/workspace/.cache
    volumes:
      - /workspace:/workspace
    working_dir: /workspace/bioinformatics_pipeline
    stdin_open: true
    tty: true